---
title: "Cystoscopy Discomfort Sample Size Simulations"
date: 2025-06-09
author: John Sperger
format: PrettyPDF-pdf
---
```{r}
#| label: libs
#| echo: false
#| include: false
library(readr)
library(dplyr)
library(purrr)
library(fabricatr)
library(DeclareDesign)
```



## Demographics

```{r}
#| label: site-demographic-summary
#| echo: false

demo_count_by_site <- readr::read_csv("data/site-demographics-count.csv")
sex_count_by_site <- readr::read_csv("data/site-indication-sex-count.csv")
```



### Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
anon_demo <- demo_count_by_site |> 
  dplyr::mutate(Site = dplyr::case_match(Site,
    "UNC" ~ "A",
    "UT Southwestern" ~ "B",
    "UAB" ~ "C",
    "Novant" ~ "D",
    "Boston VA" ~ "E",
    "Connecticut VA" ~ "F", 
    "White River Jct VA" ~ "G"))
    
anon_sex <- sex_count_by_site |>
  dplyr::mutate(Site = dplyr::case_match(Site,
    "UNC" ~ "A",
    "UT Southwestern" ~ "B",
    "UAB" ~ "C",
    "Novant" ~ "D",
    "Boston VA" ~ "E",
    "Connecticut VA" ~ "F", 
    "White River Jct VA" ~ "G"))

readr::write_csv(anon_demo, "data/anon_demo.csv")
readr::write_csv(anon_sex, "data/anon_sex.csv")
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
